config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  get '/index' => 'home#index', as: :index
  get '/mypage' => "home#mypage", as: :mypage
  get '/my_lecture' => "home#my_lecture", as: :my_lecture
  get '/my_comment' => "home#my_comment", as: :my_comment

  get '/subscription' => 'home#subscription', as: :subscription
  get '/menu' => 'home#menu', as: :menu

  root 'home#cover'

  resources :products do
    member do
      get :toggle
    end
  end

  resources :lectures do
    get :search
    member do
      get :toggle
    end
    collection do
      get :success
    end
  end

  resources :comments
  resources :orders
  resources :donations do
    collection do
      get :success
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true, optional: true
  belongs_to :user

  def get_lecture
    lecture = Lecture.find(self.commentable_id)
    return lecture
  end
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :lecture, optional: true
  belongs_to :user, optional: true
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes,as: :likable, dependent: :destroy
  has_many :donations, dependent: :nullify

  mount_uploader :image, ImageUploader

  enum category: {"언어": 0, "창업교육": 1, "직업교육": 2, "코딩": 3, "문화": 4, "콘텐츠 제작": 5}

  def self.create_lectures
    (1...6).each do |p|
      Lecture.create!(category: p, title: "Lecture #{p}", address: "Millions of refugees worldwide don't have access to education, career development, and decent jobs.
As a result of persecution, conflict, violence, human rights violations, or climate change they left behind communities and homes, but refugees have huge potential that is under-utilised. HireChance is on a quest to turn a perceived burden into a impactful opportunity for refugees and the world economy. These are the steps we are taking:")
    end
  end

  def self.create_language_lectures
    (1...6).each do |p|
      Lecture.create!(category: 0, title: "Lecture #{p}", address: "Millions of refugees worldwide don't have access to education, career development, and decent jobs.
As a result of persecution, conflict, violence, human rights violations, or climate change they left behind communities and homes, but refugees have huge potential that is under-utilised. HireChance is on a quest to turn a perceived burden into a impactful opportunity for refugees and the world economy. These are the steps we are taking:")
    end
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likable, polymorphic: true
  def get_comments
    comments = Lecture.find(self.likable_id).comments
    return comments
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  enum status: [:cart, :paid, :canceled]
  has_one :product, dependent: :nullify
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :user, optional: true

  def buy_point
    current_user.point.increment!(:amount, 10)
  end

  def donate_point
    current_user.point.decrement!(:amount, 10)
  end

end

app/models/product.rb
class Product < ApplicationRecord
  # belongs_to :order, optional: true
  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :points, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :donations, dependent: :nullify

  enum user_type: {"커피 구매자": 0, "Learner": 1}

  def has_like? like
    Like.where(likable_id: like.id).present?
  end

  def donation_ranking
    self.each do |p|
      p.donations.sum("point")
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:destroy]


  def new
    @lecture = Lecture.find(params[:lecture_id])
  end

  def create
    @lecture = Lecture.find(params[:comment][:commentable_id])
    @comment = @lecture.comments.create!(comment_params)
    # respond_to do |format|
    #   format.js
    #   # format.html
    # end
    # redirect_to lecture_path(@lecture.id)
  end

  def destroy
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content, :user_id, :commentable_type, :commentable_id, :rating)
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:cover]

  def index
    @comments_count = current_user.comments.count
    @likes_count = current_user.likes.where(likable_type: "Lecture").all.count
    @point = get_point
    @donation = current_user.donations.sum("point")
    @current_rank = User.order(:donation_total).reverse.index(current_user) + 1
  end

  def mypage
    @likes = current_user.likes.where(likable_type: "Lecture").all
    @point = get_point
    @donations = current_user.donations
    @blend_total = current_user.donations.sum("point")
    @user_rank = User.order(:donation_total).reverse.take(5)
    @current_rank = User.order(:donation_total).reverse.index(current_user) + 1
  end

  def my_lecture
    @likes = current_user.likes.where(likable_type: "Lecture").all
  end

  def my_comment
    @likes = current_user.likes.where(likable_type: "Lecture").all
  end

  def subscription
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_object, only: [:update, :show]

  def index
    @orders = Order.all
  end

  def new
  end

  def create
  end

  def edit
    @order = get_cart
    @order.update(product_id: params[:id])
    @product = Product.find(params[:id])
  end

  def update
    @order.paid!
    @order.update(order_params)
    current_user.points.first.increment!(:point, 10)
    redirect_to order_path(@order)
  end

  def show
    @product = Product.find(@order.product_id)
  end


  private

  def load_object
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:user_id, :status, :total, :zipcode, :address1, :address2, :paid_at, :name)
  end


end

app/controllers/points_controller.rb
class PointsController < ApplicationController

  before_action :authenticate_user!

  def buy
  end

  def donate
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # application_helper.rb
  def back_link(params, name: "Back", class: "back-button header-title")
    if params[:back_path].present?
      link_to name, params[:back_path], class: 'back-button header-title'
    else
      link_to name, :back, class: "back-button header-title"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/_buyer_index.html.erb
<div class="cover-slider owl-carousel bg-black">
    <div data-height="cover" class="caption">
        <div class="caption-center" style='top: 25%'>
            <h1 class="left-text font-28 bottom-15" style="margin-left: 20px">당신의 가치를</h1>
              <h1 class="left-text font-28 bottom-30" style="margin-left: 20px">블렌딩하세요.</h1><br>
            <div class="div">
              <div class="one-third center-text bottom-30">
                <h1><%= @point.point %></h1>
                보유 블렌드
              </div>
              <div class="one-third center-text bottom-30">
                <h1><%= @donation.present? ? @donation : "0" %></h1>
                기부한 블렌드
              </div>
              <div class="one-third last-column center-text bottom-30">
                <h1><%= @current_rank %></h1>
                기부 순위
              </div>
            </div>

            <p class="boxed-text-large font-18 opacity-80">
                블렌드한 당신, 오늘도 고생 많았어요
            </p>

            <a href="/subscription" class="button button-m bg-highlight round-small button-center-small shadow-large">더 알아보기</a>
        </div>
        <div class="caption-bg" style="background-image:url(/images/video.gif)"></div>
    </div>
</div>

app/views/home/_learner_index.html.erb
<div class="cover-slider owl-carousel bg-black">
    <div data-height="cover" class="caption">
        <div class="caption-center" style='top: 25%'>
            <h1 class="left-text font-28 bottom-15" style="margin-left: 20px">Blend your</h1>
              <h1 class="left-text font-28 bottom-30" style="margin-left: 20px">Values</h1><br>
            <div class="div">
              <div class="one-third center-text bottom-30">
                <h1><%= @likes_count %></h1>
                My Lectures
              </div>
              <div class="one-third center-text bottom-30">
                <h1><%= @comments_count %></h1>
                Reviews
              </div>
              <div class="one-third last-column center-text bottom-30">
                <h1>968</h1>
                Donated
              </div>
            </div>

            <p class="boxed-text-large font-18 opacity-80">
                Enhance your Career Development Education
            </p>

            <a href="/subscription" class="button button-m bg-highlight round-small button-center-small shadow-large">More</a>
        </div>
        <div class="caption-bg" style="background-image:url(/images/video.gif)"></div>
    </div>
</div>

app/views/home/index.html.erb
<% if current_user&.user_type == "Learner" %>
  <%= render 'learner_index' %>
<% else %>
  <%= render 'buyer_index' %>
<% end %>

app/views/home/my_lecture.html.erb
<div class="divider divider-margins bottom-30"></div>
<div class="content">
    <div class="content-title has-icon">
        <h3>나의 기부 강의</h3>
        <span class="color-highlight"><%= current_user&.name %>님의 강의 목록입니다</span>
        <%= link_to my_lecture_path do %><i class="fas fa-plus bg-red2-dark shadow-huge"></i><% end %>
    </div>
</div>

<% if @likes.present? %>
  <% @likes.each do |p| %>
    <a href="lectures/<%= p.likable_id%>" data-menu="menu-portfolio-instant-1" data-height="230" class="caption caption-margins round-medium shadow-huge">
        <div class="caption-top left-15 top-15">
            <div class="caption-author-left">
                <img src="images/empty.png" data-src="images/preload-logo.png" class="preload-image">
                <strong>Enabled</strong>
                <span>2 Days Ago</span>
            </div>
        </div>
        <div class="caption-top top-15 right-10">
            <div class="clear"></div>
        </div>
        <div class="caption-bottom left-20 bottom-20">
            <p class="color-white opacity-70 bottom-0 font-12"><%= Lecture.find(p.likable_id).address.truncate(50) %></p>
            <h1 class="color-white bolder font-32"><%= Lecture.find(p.likable_id).title %></h1>
        </div>
        <div class="caption-overlay bg-black opacity-70"></div>
        <% if Lecture.find(p.likable_id).image.present? %>
          <%= image_tag(Lecture.find(p.likable_id).image.large.url)%>
        <% else %>
          <div class="caption-bg bg-18"></div>
        <% end %>
    </a>
  <% end %>
<% else %>
<div class="content caption round-medium shadow-huge" style='padding: 10px'>
  기부한 강의가 없습니다
</div>
<% end %>

app/views/home/subscription.html.erb
<div class="content center-text">
    <h1>구독을 통해<br> 교육 기부에 참여하시겠습니까?</h1>
    <span class="under-heading color-highlight font-10">전 세계적으로 난민은 충분한 교육을 받지 못하고 있습니다.</span>
    <p class="boxed-text-huge top-10 bottom-50">
        아래 단계에 따라 구매를 진행해주세요:)
    </p>
</div>
<div class="content">
    <div class="content-title has-border border-green2-dark bottom-10">
        <h2>1. 원두를 구독합니다</h2>
    </div>
    <p class="bottom-30">
        진열된 원두 상품 중, 구독 혹은 구매하고 싶은 제품을 선택해주세요
    </p>
    <div data-height="250" class="caption caption-margins round-medium shadow-large">
        <div class="caption-bottom center-text bottom-25">
            <h1 class="font-28 color-white">원두 보러가기</h1>
            <span class="under-heading color-highlight font-11">공정무역을 통한 콜롬비아산 원두</span>
        </div>
        <div class="caption-overlay bg-gradient-fade"></div>
        <div class="caption-bg bg-9" style="background-image: url('/images/coffee_example.jpeg')"></div>
    </div>
</div>



<div class="content">
    <div class="content-title has-border border-red2-dark bottom-10">
        <h2>2. 기부 강의를 선택합니다</h2>
    </div>
    <p class="top-10 bottom-50">
        총 결제액의 25%로 선택하신 강의에 기부가 됩니다.
    </p>
    <div data-height="250" class="caption caption-margins round-medium shadow-large">
        <div class="caption-bottom center-text bottom-25">
            <h1 class="font-28 color-white">강의 둘러보기</h1>
            <span class="under-heading color-highlight font-11">난민들의 교육권을 도와주세요</span>
        </div>
        <div class="caption-overlay bg-gradient-fade"></div>
        <div class="caption-bg bg-9" style="background-image: url('/images/education.jpeg')"></div>
    </div>
</div>

<div class="content">
    <div class="content-title has-border border-yellow2-dark bottom-10">
        <h2>3. 구독 내역을 확인합니다</h2>
    </div>
    <p class="top-10 bottom-50">
        내가 구독한 제품과 함께 기부를 진행한 강의들을 확인할 수 있습니다.
    </p>
    <div data-height="250" class="caption caption-margins round-medium shadow-large">
        <div class="caption-bottom center-text bottom-25">
            <h1 class="font-28 color-white">정기구독 바로시작</h1>
            <span class="under-heading color-highlight font-11">교육 기부 참여하기</span>
        </div>
        <div class="caption-overlay bg-gradient-fade"></div>
        <div class="caption-bg bg-9" style="background-image: url('/images/computer.jpeg')"></div>
    </div>
</div>
<div class="content center-text">
    <h1>함께 가치소비를 시작해요</h1>
    <span class="under-heading color-highlight font-10">당신의 작은 소비로 난민의 인생을 바꿀 수 있습니다</span>
    <p class="boxed-text-huge top-10 bottom-30">
        HireChance는 100% 공정한 전문 커피를 판매함으로써 전 세계 난민들을 위한 온라인 기술과 언어 교육을 위한 경력 구축에 자금을 지원합니다.
    </p>
    <a href="/products" class="button button-m button-center-large bg-highlight button-circle shadow-huge bottom-30">정기구독 상품보기</a>
</div>

<div class="divider divider-margins top-10"></div>
<div class="visible-slider2-small single-slider owl-carousel owl-no-dots">
    <div class="slider-item center-text">
      <%= link_to subscription_path do %>
        <div data-height="250" class="caption round-medium shadow-huge">
            <div class="caption-bottom center-text bottom-25">
                <h1 class="font-28 color-white">정기구독 알아보기</h1>
                <span class="under-heading color-highlight font-11">커피 정기구독으로 교육 기부에 참여하세요</span>
            </div>
            <div class="caption-overlay bg-gradient-fade"></div>
            <div class="caption-bg bg-3" style="background-image: url(/images/video.gif)"></div>
        </div>
        <p class="boxed-text-huge top-10">
            난민과 상생하는 사회를 함께 만들어 나갈 수 있습니다:)
        </p>
      <% end %>
    </div>
    <div class="slider-item center-text">
      <%= link_to lectures_path do %>
        <div data-height="250" class="caption round-medium shadow-huge">
            <div class="caption-bottom center-text bottom-25">
                <h1 class="font-28 color-white">교육 강좌 선택하기</h1>
                <span class="under-heading color-highlight font-11">현재 기부 가능한 교육 강좌 리스트입니다</span>
            </div>
            <div class="caption-overlay bg-gradient-fade"></div>
            <div class="caption-bg bg-9"  style="background-image: url(/images/hand.jpeg)"></div>
        </div>
        <p class="boxed-text-huge top-10">
            난민들이 새로운 사회에 적응할 수 있도록, 원하는 강좌를 직접 골라 기부하실 수 있습니다.
        </p>
        <% end %>
    </div>
    <div class="slider-item center-text">
      <%= link_to products_path do %>
        <div data-height="250" class="caption round-medium shadow-huge">
            <div class="caption-bottom center-text bottom-25">
                <h1 class="font-28 color-white">콜롬비아산 원두</h1>
                <span class="under-heading color-highlight font-11">공정무역으로 농부들에게 정당 수익을 제공합니다</span>
            </div>
            <div class="caption-overlay bg-gradient-fade"></div>
            <div class="caption-bg bg-9" style="background-image:url(/images/cover_02.jpeg)"></div>
        </div>
        <p class="boxed-text-huge top-10">
            우리의 커피는 매우 질 좋은 제품이고, 농부에게도 정당한 수익을 배분합니다.
        </p>
      <% end %>
    </div>
</div>

<!-- <div class="content">
    <p class="center-text bottom-20">
        <a href="#" class="icon icon-m bg-facebook icon-circle shadow-huge"><i class="fab fa-facebook-f"></i></a>
        <a href="#" class="left-15 right-15 icon icon-m bg-phone icon-circle shadow-huge"><i class="fa fa-phone"></i></a>
        <a href="#" class="icon icon-m bg-twitter icon-circle shadow-huge"><i class="fab fa-twitter"></i></a>
    </p>
</div> -->

<div class="divider divider-margins"></div>

<div class="content center-text">
    <h1>12, 043</h1>
    <span class="under-heading color-highlight font-10">개의 교육 강의가 기부되었습니다.</span>
    <p class="boxed-text-huge top-10">
        Hirechance의 기부자님들 덕분에 수 많은 난민들이 교육의 기회를 제공받았습니다.
    </p>
    <a href="/subscription" class="button button-s button-center-medium bg-highlight button-circle shadow-huge bottom-40">더 알아보기</a>
</div>

<div class="divider divider-margins"></div>


<div data-height="150" class="caption caption-margins round-medium top-20 shadow-huge">
    <div class="caption-top top-10 right-10">
        <a href="#" class="icon icon-xs float-right"><i class="fa fa-question-circle font-24"></i></a>
        <div class="clear"></div>
    </div>
    <a href="https://amnesty.or.kr/campaign/%EC%88%AB%EC%9E%90%EB%A1%9C-%EB%B3%B4%EB%8A%94-%EC%84%B8%EA%B3%84-%EB%82%9C%EB%AF%BC/" class="caption-bottom left-20 bottom-20" target='_blank'>
        <p class="color-white opacity-60 bottom-0">아셨나요?</p>
        <h1 class="color-white font-22">전 세계에 2,590만명의 난민이 있으며<br>140만명 이상이 재정착을 필요로 합니다.</h1>
    </a>
    <div class="caption-overlay bg-black opacity-80"></div>
    <div class="caption-bg bg-16"></div>
</div>

<div class="divider divider-margins"></div>

<div class="content center-text">
    <h1>한국, 그리고 세계의 난민</h1>
    <span class="under-heading color-highlight font-10">전 세계적으로 난민은 어떤 생활을 하고 있을까요?</span>
    <p class="boxed-text-huge top-10 bottom-50">
        전 세계적으로 난민들은 교육을 제대로 받지 못하고 있으며, 사회적 약자에서 벗어나지 못하고 있습니다.
    </p>
</div>

<div class="content bottom-0">
    <a href="https://www.bbc.com/korean/news-44632261" class="clear" target='_blank'>
        <div class="one-half small-half">
            <div data-height="95" class="caption round-small shadow-huge">
                <div class="caption-image">
                    <img src="https://ichef.bbci.co.uk/news/660/cpsprodpb/10BAC/production/_102242586_yemen_refugee_2.png" class="responsive-image">
                </div>
            </div>
        </div>
        <div class="one-half large-half last-column">
            <h5 class="color-theme">제주 예멘: 예멘인 난민신청자들의 현실</h5>
            <span class="under-heading font-10 color-highlight">BBC 코리아</span>
            <p class="font-12">
                지난 21일 제주시의 한 관광호텔 앞에 4명의 남성이 서성이고 있었다. 이들은 지난 5월 제주에 들어온 예멘 출신의 난민신청자다.
            </p>
        </div>
    </a>
    <a href="https://nancen.org/2033" class="clear" target="_blank">
        <div class="one-half small-half">
            <div data-height="95" class="caption round-small shadow-huge">
                <div class="caption-image">
                    <img src="https://images.unsplash.com/photo-1579296440601-efe78a19fa91?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80" class="responsive-image">
                </div>
            </div>
        </div>
        <div class="one-half large-half last-column">
            <h5 class="color-theme">[통계] 국내 난민 현황</h5>
            <span class="under-heading font-10 color-highlight">난민인권센터</span>
            <p class="font-12">
                난민인권센터는 2009년부터 국내난민현황을 모니터링 하고 있습니다. 올해 초 난민 관련 정부 각 부처에 난민 신청, 인정, 심사,..
            </p>
        </div>
    </a>
    <a href="https://amnesty.or.kr/campaign/%EC%88%AB%EC%9E%90%EB%A1%9C-%EB%B3%B4%EB%8A%94-%EC%84%B8%EA%B3%84-%EB%82%9C%EB%AF%BC/" target="_blank" class="clear">
        <div class="one-half small-half">
            <div data-height="95" class="caption round-small shadow-huge">
                <div class="caption-image">
                    <img src="https://amnesty.or.kr/wp-content/uploads/2019/06/Refugees-graphic1_Web_June-2019_Final_kr.jpg" class="responsive-image">
                </div>
            </div>
        </div>
        <div class="one-half large-half last-column">
            <h5 class="color-theme">숫자로 보는 세계 난민</h5>
            <span class="under-heading font-10 color-highlight">국제 엠네스티</span>
            <p class="font-12">
              전세계적으로 난민의 수는 몇 명이나 될까? 이 난민들이 재정착하는 곳은 어디일까?
            </p>
        </div>
    </a>
    <div class="clear"></div>
</div>

<div class="divider divider-margins"></div>

<div data-height="330" class="caption round-medium shadow-huge caption-margins">
    <div class="caption-center">
        <h1 class="center-text color-white font-32">고품질 원두만을 판매</h1>
        <p class="center-text color-white opacity-60 under-heading font-11">정기구독 고객님들의 높은 만족도가 증명합니다.</p>
        <p class="boxed-text-large color-white">
          우리는 커피 농부들과 직접적인 관계를 구축하고 그들이 평균적인 근무 조건, 임금, 그리고 그들의 특산품 커피가 시장 가격보다 높은 가격에 팔리도록 함으로써 그들의 노고를 기립니다.
        </p>
        <a href="/products" class="button button-circle button-center-small button-s bg-highlight">상품 상세</a>
    </div>
    <div class="caption-overlay bg-black opacity-80"></div>
    <div class="caption-bg bg-14" style="background-image:url(/images/cover_02.jpeg)"></div>
</div>

<div class="divider divider-margins"></div>

<div class="content center-text">
    <h1>구독 제품 소개</h1>
    <span class="under-heading color-highlight font-10">공정 무역 콜롬비아산 원두</span>
    <p class="boxed-text-huge top-10 bottom-30">
      커피를 통해 가치소비를, 그리고 난민들을 위한 교육 기부를 한번에 하실 수 있습니다
    </p>
</div>

<div class="visible-slider-small double-slider owl-carousel owl-no-dots bottom-0">

    <a href="https://hirechance.org/product/esperanza-drip-bag-coffee-subscription/" class="slider-item" target="_blank">
        <div data-height="250" class="caption round-medium shadow-huge">
            <div class="caption-top left-15 top-15">
                <h1 class="color-white font-30">Esperanza</h1>
                <p class="under-heading color-white font-10">더보기 클릭</p>
            </div>
            <div class="caption-bottom bottom-15 left-15 right-15">
                <p class="color-white opacity-80 bottom-0">
                    드립백 커피 정기구독<br>
                    ₩55,000 – ₩660,000
                </p>
            </div>
            <div class="caption-overlay bg-black opacity-70"></div>
            <div class="caption-bg bg-1" style="background-image: url('/images/coffee_sample.png')"></div>
        </div>
    </a>
    <a href="https://hirechance.org/product/esperanza-ground-coffee-subscription/" class="slider-item"  target="_blank">
        <div data-height="250" class="caption round-medium shadow-huge">
            <div class="caption-top left-15 top-15">
                <h1 class="color-white font-30">Esperanza</h1>
                <p class="under-heading color-white font-10">더보기 클릭</p>
            </div>
            <div class="caption-bottom bottom-15 left-15 right-15">
                <p class="color-white opacity-80 bottom-0">
                    원두 커피 분말 정기구독<br>
                    ₩55,000 – ₩660,000
                </p>
            </div>
            <div class="caption-overlay bg-black opacity-70"></div>
            <div class="caption-bg bg-2" style="background-image: url('/images/coffee_sample.png')"></div>
        </div>
    </a>
    <a href="https://hirechance.org/product/esperanza-whole-bean-coffee-subscription/" class="slider-item"  target="_blank">
        <div data-height="250" class="caption round-medium shadow-huge">
            <div class="caption-top left-15 top-15">
                <h1 class="color-white font-30">Esperanza</h1>
                <p class="under-heading color-white font-10">더보기 클릭</p>
            </div>
            <div class="caption-bottom bottom-15 left-15 right-15">
                <p class="color-white opacity-80 bottom-0">
                    원두커피 정기구독<br>
                    ₩55,000 – ₩660,000
                </p>
            </div>
            <div class="caption-overlay bg-black opacity-70"></div>
            <div class="caption-bg bg-3" style="background-image: url('/images/coffee_sample.png')"></div>
        </div>
    </a>

</div>

<div class="divider divider-margins"></div>

<div class="content center-text">
    <h1>함께 가치소비를 시작해요</h1>
    <span class="under-heading color-highlight font-10">당신의 작은 소비로 난민의 인생을 바꿀 수 있습니다</span>
    <p class="boxed-text-huge top-10 bottom-30">
        HireChance는 100% 공정한 전문 커피를 판매함으로써 전 세계 난민들을 위한 온라인 기술과 언어 교육을 위한 경력 구축에 자금을 지원합니다.
    </p>
    <a href="/subscription" class="button button-m button-center-large bg-highlight button-circle shadow-huge bottom-30">정기구독 바로가기</a>
</div>




<div class="menu-hider"></div>