config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  get '/index' => 'home#index', as: :index
  get '/mypage' => "home#mypage", as: :mypage
  get '/my_lecture' => "home#my_lecture", as: :my_lecture
  get '/my_comment' => "home#my_comment", as: :my_comment

  get '/subscription' => 'home#subscription', as: :subscription
  get '/menu' => 'home#menu', as: :menu

  root 'home#cover'

  resources :products do
    member do
      get :toggle
    end
  end

  resources :lectures do
    get :search
    member do
      get :toggle
    end
    collection do
      get :success
    end
  end

  resources :comments
  resources :orders
  resources :donations do
    collection do
      get :success
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :lecture, optional: true
  belongs_to :user, optional: true
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_object, only: [:show, :success]

  def index
    @donations = Donation.all
  end

  def new
    @donation = Donation.new
    @lecture = Lecture.find(params[:lecture_id])
  end

  def create
    @donation = Donation.create(donation_params)
    point = params[:donation][:point].to_i
    current_user.points.first.decrement!(:point, point)
    current_user.increment!(:donation_total, point)
    redirect_to success_donations_path(id: @donation)
  end

  # def edit
  #   @donation = get_donation
  #   @donation.update(lecture_id: params[:id])
  #   @lecture = Lecture.find(params[:id])
  # end
  #
  # def update
  #   @donation.update(donation_params)
  #   current_user.points.first.decrement!(:point, params[:point])
  #   redirect_to donation_path(@donation)
  # end

  def show
    @product = Product.find(@order.product_id)
  end

  def success
  end


  private

  def load_object
    @donation = Donation.find(params[:id])
  end

  def donation_params
    params.require(:donation).permit(:lecture_id, :user_id, :point)
  end

end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/new.html.erb
<div data-height="cover" style="top: 250px">
  <div class="caption-center" style="margin-top: 0px;">
    <div class="content bottom-0">
      <div style="padding: 30px; padding-top: 40px">
        <h1 class="color-black font-30 top-30">블렌드 기부하기</h1>
        <%= form_for @donation do |f| %>
        <div class="input-style input-style-1 input-required top-20">
          <h5>보유 블렌드: <%= current_user.points.first.point %></h5>
          <span>기부 블렌드</span>
          <em>(필수)</em>
          <%= f.text_field :point, autofocus: true, autocomplete: "name", placeholder: "기부 블렌드 입력"%>
        </div>
        <div class="clear"></div>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :lecture_id, value: @lecture.id %>
        <div class="back-button button button-full button-m round-small shadow-huge bg-highlight top-30">
          <%= f.submit "기부하기" , style: "color: white; background: #F6BB42"%>
        </div>
      <% end %>
    </div>
    <div class="divider divider-margins"></div>
    <h3 class="color-black font-15 top-30">기부 강의</h3><Br>
    <%= link_to lecture_path(@lecture.id), class: "external" do %>
    <div class="clear">
      <div class="one-half small-half">
        <div data-height="140" class="caption">
          <div class="caption-image">
            <% if @lecture.image&.present? %>
              <img src="<%= @lecture.image.url %>" class="responsive-image round-medium">
            <% else %>
              <img src="<%= @lecture.image_link.present? ? @lecture.image_link : "/images/pictures/28s.jpg"%>" class="responsive-image round-medium">
            <% end %>
          </div>
        </div>
      </div>
      <div class="one-half large-half last-column">
        <h5 class="color-theme"><%= @lecture.title %></h5>
        <span class="under-heading font-10 color-highlight"><%= @lecture.category %></span>
        <p class="font-12 bottom-10">
          <%= @lecture.address.truncate(100) %>
        </p>
      </div>
    </div>
  <% end %>
</div>
</div>
</div>

app/views/donations/success.html.erb
<div class="cover-slider owl-carousel bg-white">
  <div data-height="cover" class="caption">
    <div class="caption-center" style='top: 35%'>
      <p class="center-text font-20 bottom-15" style="color:black">
        <img src="/images/congrats.gif" style="width: 200px; margin-bottom: 50px">
        <span class="bolder"><%= @donation.lecture.title %></span> 강의에<Br>
        <span class="bolder"><%= @donation.point %></span> 블렌드를<br>
          기부하였습니다!</p><Br><br>
          <a href="/index" class="external button button-m bg-highlight round-small button-center-small shadow-large" style="width: 100px">확인</a><br>
    </div>
    <!-- <div class="caption-overlay bg-black opacity-25"></div> -->
    <div class="caption-bg" style="background-color: white;"></div>
  </div>
</div>