config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  get '/index' => 'home#index', as: :index
  get '/mypage' => "home#mypage", as: :mypage
  get '/my_lecture' => "home#my_lecture", as: :my_lecture
  get '/my_comment' => "home#my_comment", as: :my_comment

  get '/subscription' => 'home#subscription', as: :subscription
  get '/menu' => 'home#menu', as: :menu

  root 'home#cover'

  resources :products do
    member do
      get :toggle
    end
  end

  resources :lectures do
    get :search
    member do
      get :toggle
    end
    collection do
      get :success
    end
  end

  resources :comments
  resources :orders
  resources :donations do
    collection do
      get :success
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true, optional: true
  belongs_to :user

  def get_lecture
    lecture = Lecture.find(self.commentable_id)
    return lecture
  end
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :lecture, optional: true
  belongs_to :user, optional: true
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes,as: :likable, dependent: :destroy
  has_many :donations, dependent: :nullify

  mount_uploader :image, ImageUploader

  enum category: {"언어": 0, "창업교육": 1, "직업교육": 2, "코딩": 3, "문화": 4, "콘텐츠 제작": 5}

  def self.create_lectures
    (1...6).each do |p|
      Lecture.create!(category: p, title: "Lecture #{p}", address: "Millions of refugees worldwide don't have access to education, career development, and decent jobs.
As a result of persecution, conflict, violence, human rights violations, or climate change they left behind communities and homes, but refugees have huge potential that is under-utilised. HireChance is on a quest to turn a perceived burden into a impactful opportunity for refugees and the world economy. These are the steps we are taking:")
    end
  end

  def self.create_language_lectures
    (1...6).each do |p|
      Lecture.create!(category: 0, title: "Lecture #{p}", address: "Millions of refugees worldwide don't have access to education, career development, and decent jobs.
As a result of persecution, conflict, violence, human rights violations, or climate change they left behind communities and homes, but refugees have huge potential that is under-utilised. HireChance is on a quest to turn a perceived burden into a impactful opportunity for refugees and the world economy. These are the steps we are taking:")
    end
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likable, polymorphic: true
  def get_comments
    comments = Lecture.find(self.likable_id).comments
    return comments
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  enum status: [:cart, :paid, :canceled]
  has_one :product, dependent: :nullify
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :user, optional: true

  def buy_point
    current_user.point.increment!(:amount, 10)
  end

  def donate_point
    current_user.point.decrement!(:amount, 10)
  end

end

app/models/product.rb
class Product < ApplicationRecord
  # belongs_to :order, optional: true
  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :points, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :donations, dependent: :nullify

  enum user_type: {"커피 구매자": 0, "Learner": 1}

  def has_like? like
    Like.where(likable_id: like.id).present?
  end

  def donation_ranking
    self.each do |p|
      p.donations.sum("point")
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:destroy]


  def new
    @lecture = Lecture.find(params[:lecture_id])
  end

  def create
    @lecture = Lecture.find(params[:comment][:commentable_id])
    @comment = @lecture.comments.create!(comment_params)
    # respond_to do |format|
    #   format.js
    #   # format.html
    # end
    # redirect_to lecture_path(@lecture.id)
  end

  def destroy
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content, :user_id, :commentable_type, :commentable_id, :rating)
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:cover]

  def index
    @comments_count = current_user.comments.count
    @likes_count = current_user.likes.where(likable_type: "Lecture").all.count
    @point = get_point
    @donation = current_user.donations.sum("point")
    @current_rank = User.order(:donation_total).reverse.index(current_user) + 1
  end

  def mypage
    @likes = current_user.likes.where(likable_type: "Lecture").all
    @point = get_point
    @donations = current_user.donations
    @blend_total = current_user.donations.sum("point")
    @user_rank = User.order(:donation_total).reverse.take(5)
    @current_rank = User.order(:donation_total).reverse.index(current_user) + 1
  end

  def my_lecture
    @likes = current_user.likes.where(likable_type: "Lecture").all
  end

  def my_comment
    @likes = current_user.likes.where(likable_type: "Lecture").all
  end

  def subscription
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_object, only: [:update, :show]

  def index
    @orders = Order.all
  end

  def new
  end

  def create
  end

  def edit
    @order = get_cart
    @order.update(product_id: params[:id])
    @product = Product.find(params[:id])
  end

  def update
    @order.paid!
    @order.update(order_params)
    current_user.points.first.increment!(:point, 10)
    redirect_to order_path(@order)
  end

  def show
    @product = Product.find(@order.product_id)
  end


  private

  def load_object
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:user_id, :status, :total, :zipcode, :address1, :address2, :paid_at, :name)
  end


end

app/controllers/points_controller.rb
class PointsController < ApplicationController

  before_action :authenticate_user!

  def buy
  end

  def donate
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @point = get_point
  end

  def update
  end

  def toggle
    @product = Product.find(params[:id])
    if product_toggle = current_user.likes.where(likable_id: @product.id).last
      product_toggle.destroy
      # respond_to do |format|
      #   format.js
      # end
    else
      @toggle = Like.create!(likable_id: @product.id, likable_type: "Product", user_id: current_user.id)
      # respond_to do |format|
      #   format.js
      # end
    end
    redirect_to product_path(@product)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  # application_helper.rb
  def back_link(params, name: "Back", class: "back-button header-title")
    if params[:back_path].present?
      link_to name, params[:back_path], class: 'back-button header-title'
    else
      link_to name, :back, class: "back-button header-title"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<div class="content center-text">
  <h1>소비하고, 가치하자</h1>
  <span class="under-heading color-highlight font-10">당신의 작은 소비로 난민의 인생을 바꿀 수 있습니다</span>
  <p class="boxed-text-huge top-10 bottom-30">
    Blend는 HireChance의 맛있는 공정무역커피와 함께 난민 교육 환경 개선을 위해 가치를 더합니다.
  </p>
</div>
<div class="divider divider-margins"></div>

<% @products&.each do |product| %>
<div class="one-half" style="margin-bottom: 20px">
  <a href="<%= product_path(product.id)%>" data-menu="menu-instant-1" data-height="150" class="caption caption-margins round-medium shadow-huge" style="margin-bottom: 10px">
    <div class="caption-top right-text top-10 right-15">
      <span class="color-white ultrabold font-9">더보기</span>
    </div>
    <div class="caption-bottom left-20 bottom-20">
      <!-- <p class="color-white opacity-70 bottom-0 font-12"><%= product.sub_title %></p> -->
    </div>
    <div class="caption-overlay bg-black opacity-10"></div>
    <div class="caption-bg bg-11" style="background-image: url(<%= product.image.present? ? product.image.url : '/images/coffee_sample.png' %>)"></div>
  </a>
  <span class="text-center font-15"><%= product.title %></span>
  <span class="text-center font-14">₩<%= product.price %></span>
</div>
<% end %>
<!-- Modal View -->
<!-- Remember to use a unique ID and target it using the data-menu="menu-instant-1" on your button-->
<div id="menu-instant-1" class="menu-box" data-menu-type="menu-box-modal" data-menu-height="100%" data-menu-width="100%" data-menu-effect="menu-over">

  <div data-height="380" class="caption shadow-huge">
    <div class="caption-top left-15 top-15">
      <!-- <div href="#" class="caption-author-left"> <img src="images/empty.png" data-src="images/preload-logo.png" class="preload-image"> <strong>Enabled</strong> <span>2 Days Ago</span> </div> -->
    </div>
    <div class="caption-top top-10 right-10">
      <a href="#" class="close-menu icon icon-xs float-right">
        <i class="fa fa-times-circle color-red2-light font-24"></i>
      </a>
    </div>
    <div class="caption-bottom bottom-20 left-20">
      <h1 class="color-white font-30 line-height-huge">Esperanza 드립백</h1>
      <p class="color-white opacity-50">
        정기구독 ₩55,000 – ₩660,000
      </p>
    </div>
    <div class="caption-overlay bg-black opacity-80"></div>
    <div class="caption-bg bg-11" style="background-image: url('/images/coffee_sample.png')"></div>
  </div>
  <div class="content">
    <p>
      Esperanza는 Quindio 지역의 Insula 농장에서 생산 된 맛있는 원두 커피입니다. 이 커피는 J. Hernandez에 의해 전문적으로 재배되었으며 컵핑 점수는 85.75입니다. 이 제품은 매주 또는 격주로 배달되는 1, 3 또는 6 개월의 구독으로 10 개의 '드립 백'커피 백으로 구성됩니다. ‘원두’와‘원두커피 분말'을 구독 할 수도 있습니다. 이 커피 판매의 25 %가 난민 경력 개발 교육에 직접 기부됩니다.
    </p>
    <div class="divider"></div>
  </div>
  <a href="https://hirechance.org/product/esperanza-drip-bag-coffee-subscription/" target="_blank">
    <div data-height="70" class="caption caption-margins round-medium">
      <div class="caption-center left-20">
        <p class="bottom-0">
          <strong>아래 링크에서 더욱 자세한 정보를 확인하세요</strong>
        </p>
        <p class="bottom-0 font-10 under-heading">www.hirechance.com</p>
      </div>
      <div class="caption-center right-10">
        <i class="fa fa-chevron-right float-right opacity-15"></i>
      </div>
      <div class="caption-overlay bg-black opacity-10"></div>
    </div>
  </a>

  <div class="content">
    <div class="divider"></div>
    <h4>배송안내:</h4>
    <p class="color-highlight font-10 under-heading bottom-10">Delivery</p>
    <p>
      정오까지 결제 완료된 주문에 한해 당일 발송되며, 주말/공휴일은 발송이 없습니다<br>
      상품의 재고 상황에 따라 하루정도 지연 발송 될 수 있습니다.<br>
      상품은 CJ대한통운으로 발송되며, 구매 후 2-5일 이내 수령이 가능합니다.<br>
      (주말/공휴일 제외)
    </p>
    <div class="divider"></div>
  </div>

  <div class="content">
    <div class="divider"></div>
    <h4>교환/반품/환불:</h4>
    <p class="color-highlight font-10 under-heading bottom-10">Exchange / Return / Refund:</p>
    <p>
      HireChance 의 모든 원두 제품은 로스팅 후 7일 이내에 판매합니다.<br>
      아래와 같은 경우 교환/반품/환불이 불가능하오니 주문 시 참고해 주시기 바랍니다.<br>
      – 고객님의 단순 변심에 의한 경우<br>
      – 원두 제품을 분쇄해 주문 하셨을 경우<br>
      – 제품이 개봉 되었거나 포장이 훼손되었을 경우
    </p>
    <div class="divider"></div>
  </div>

  <div class="divider divider-margins"></div>

  <a href="#" class="close-menu button button-full button-m button-margins round-small shadow-huge bg-red2-dark bottom-30">닫기</a>
</div>

<!-- Top View -->
<!-- Remember to use a unique ID and target it using the data-menu="menu-instant-1" on your button-->
<div id="menu-instant-2" class="menu-box" data-menu-type="menu-box-top" data-menu-height="100%" data-menu-width="100%" data-menu-effect="menu-over">

  <div data-height="380" class="caption shadow-huge">
    <div class="caption-top left-15 top-15">
      <!-- <div href="#" class="caption-author-left"> <img src="images/empty.png" data-src="images/preload-logo.png" class="preload-image"> <strong>Enabled</strong> <span>2 Days Ago</span> </div> -->
    </div>
    <div class="caption-top top-10 right-10">
      <a href="#" class="close-menu icon icon-xs float-right">
        <i class="fa fa-times-circle color-red2-light font-24"></i>
      </a>
    </div>
    <div class="caption-bottom bottom-20 left-20">
      <h1 class="color-white font-30 line-height-huge">Esperanza 원두 커피 분말</h1>
      <p class="color-white opacity-50">
        정기구독 ₩55,000 – ₩660,000
      </p>
    </div>
    <div class="caption-overlay bg-black opacity-80"></div>
    <div class="caption-bg bg-18" style="background-image: url('/images/coffee_sample.png')"></div>
  </div>
  <div class="content">
    <p>
      Esperanza는 Quindio 지역의 Insula 농장에서 생산 된 맛있는 원두 커피입니다. 이 커피는 J. Hernandez에 의해 전문적으로 재배되었으며 컵핑 점수는 85.75입니다. 이 제품은 매주 또는 격주로 배달되는 1, 3 또는 6 개월의 구독으로 10 개의 '원두 커피 분말'로 구성됩니다. ‘원두’와‘드립백'을 구독 할 수도 있습니다. 이 커피 판매의 25 %가 난민 경력 개발 교육에 직접 기부됩니다.
    </p>
    <div class="divider"></div>
  </div>

  <a href="https://hirechance.org/product/esperanza-ground-coffee-subscription/" target="_blank">
    <div data-height="70" class="caption caption-margins round-medium">
      <div class="caption-center left-20">
        <p class="bottom-0">
          <strong>아래 링크에서 더욱 자세한 정보를 확인하세요</strong>
        </p>
        <p class="bottom-0 font-10 under-heading">www.hirechance.com</p>
      </div>
      <div class="caption-center right-10">
        <i class="fa fa-chevron-right float-right opacity-15"></i>
      </div>
      <div class="caption-overlay bg-black opacity-10"></div>
    </div>
  </a>

  <div class="content">
    <div class="divider"></div>
    <h4>배송안내:</h4>
    <p class="color-highlight font-10 under-heading bottom-10">Delivery</p>
    <p>
      정오까지 결제 완료된 주문에 한해 당일 발송되며, 주말/공휴일은 발송이 없습니다<br>
      상품의 재고 상황에 따라 하루정도 지연 발송 될 수 있습니다.<br>
      상품은 CJ대한통운으로 발송되며, 구매 후 2-5일 이내 수령이 가능합니다.<br>
      (주말/공휴일 제외)
    </p>
    <div class="divider"></div>
  </div>

  <div class="content">
    <div class="divider"></div>
    <h4>교환/반품/환불:</h4>
    <p class="color-highlight font-10 under-heading bottom-10">Exchange / Return / Refund:</p>
    <p>
      HireChance 의 모든 원두 제품은 로스팅 후 7일 이내에 판매합니다.<br>
      아래와 같은 경우 교환/반품/환불이 불가능하오니 주문 시 참고해 주시기 바랍니다.<br>
      – 고객님의 단순 변심에 의한 경우<br>
      – 원두 제품을 분쇄해 주문 하셨을 경우<br>
      – 제품이 개봉 되었거나 포장이 훼손되었을 경우
    </p>
    <div class="divider"></div>
  </div>

  <div class="divider divider-margins"></div>

  <a href="#" class="close-menu button button-full button-m button-margins round-small shadow-huge bg-red2-dark bottom-30">닫기</a>
</div>

<!-- Right View -->
<!-- Remember to use a unique ID and target it using the data-menu="menu-instant-1" on your button-->
<div id="menu-instant-3" class="menu-box" data-menu-type="menu-box-right" data-menu-height="100%" data-menu-width="100%" data-menu-effect="menu-over">

  <div data-height="380" class="caption shadow-huge">
    <div class="caption-top left-15 top-15">
      <!-- <div href="#" class="caption-author-left"> <img src="images/empty.png" data-src="images/preload-logo.png" class="preload-image"> <strong>Enabled</strong> <span>2 Days Ago</span> </div> -->
    </div>
    <div class="caption-top top-10 right-10">
      <a href="#" class="close-menu icon icon-xs float-right">
        <i class="fa fa-times-circle color-red2-light font-24"></i>
      </a>
    </div>
    <div class="caption-bottom bottom-20 left-20">
      <h1 class="color-white font-30 line-height-huge">Esperanza 원두</h1>
      <p class="color-white opacity-50">
        정기구독 ₩55,000 – ₩660,000
      </p>
    </div>
    <div class="caption-overlay bg-black opacity-80"></div>
    <div class="caption-bg bg-12" style="background-image: url('/images/coffee_sample.png')"></div>
  </div>
  <div class="content">
    <p>
      Esperanza는 Quindio 지역의 Insula 농장에서 생산 된 맛있는 원두 커피입니다. 이 커피는 J. Hernandez에 의해 전문적으로 재배되었으며 컵핑 점수는 85.75입니다. 이 제품은 매주 또는 격주로 배달되는 1, 3 또는 6 개월의 구독으로 10 개의 '원두'로 구성됩니다. ‘원두 커피 분말’과 ‘드립백'을 구독 할 수도 있습니다. 이 커피 판매의 25 %가 난민 경력 개발 교육에 직접 기부됩니다.
    </p>
    <div class="divider"></div>
  </div>

  <a href="https://hirechance.org/product/esperanza-whole-bean-coffee-subscription/" target="_blank">
    <div data-height="70" class="caption caption-margins round-medium">
      <div class="caption-center left-20">
        <p class="bottom-0">
          <strong>아래 링크에서 더욱 자세한 정보를 확인하세요</strong>
        </p>
        <p class="bottom-0 font-10 under-heading">www.hirechance.com</p>
      </div>
      <div class="caption-center right-10">
        <i class="fa fa-chevron-right float-right opacity-15"></i>
      </div>
      <div class="caption-overlay bg-black opacity-10"></div>
    </div>
  </a>

  <div class="content">
    <div class="divider"></div>
    <h4>배송안내:</h4>
    <p class="color-highlight font-10 under-heading bottom-10">Delivery</p>
    <p>
      정오까지 결제 완료된 주문에 한해 당일 발송되며, 주말/공휴일은 발송이 없습니다<br>
      상품의 재고 상황에 따라 하루정도 지연 발송 될 수 있습니다.<br>
      상품은 CJ대한통운으로 발송되며, 구매 후 2-5일 이내 수령이 가능합니다.<br>
      (주말/공휴일 제외)
    </p>
    <div class="divider"></div>
  </div>

  <div class="content">
    <div class="divider"></div>
    <h4>교환/반품/환불:</h4>
    <p class="color-highlight font-10 under-heading bottom-10">Exchange / Return / Refund:</p>
    <p>
      HireChance 의 모든 원두 제품은 로스팅 후 7일 이내에 판매합니다.<br>
      아래와 같은 경우 교환/반품/환불이 불가능하오니 주문 시 참고해 주시기 바랍니다.<br>
      – 고객님의 단순 변심에 의한 경우<br>
      – 원두 제품을 분쇄해 주문 하셨을 경우<br>
      – 제품이 개봉 되었거나 포장이 훼손되었을 경우
    </p>
    <div class="divider"></div>
  </div>

  <div class="divider divider-margins"></div>

  <a href="#" class="close-menu button button-full button-m button-margins round-small shadow-huge bg-red2-dark bottom-30">닫기</a>
</div>
<div class="divider divider-margins"></div>

app/views/products/show.html.erb
<div>

  <div data-height="380" class="caption shadow-huge">
    <div class="caption-top left-15 top-15">
      <!-- <div href="#" class="caption-author-left"> <img src="images/empty.png" data-src="images/preload-logo.png" class="preload-image"> <strong>Enabled</strong> <span>2 Days Ago</span> </div> -->
    </div>
    <div class="caption-bottom bottom-20 left-20">
      <h1 class="color-white font-30 line-height-huge"><%= @product.title %></h1>
      <p class="color-white opacity-50">
        <%= @product.price %>
      </p>
    </div>
    <div class="caption-overlay bg-black opacity-80"></div>
    <div class="caption-bg bg-11" style="background-image: url('/images/coffee_sample.png')"></div>
  </div>
  <div class="content">
    <% if current_user %>
      <div class="one-half">
        <%= link_to current_user.likes.where(likable_id: @product.id).present? ? "찜 취소" : "찜하기", toggle_product_path(@product), class: current_user.likes.where(likable_id: @product.id ).present? ?
        "button button-m button-full button-margins round-small shadow-huge bg-red1-light bottom-30 toggle-button" : "button button-m button-full button-margins round-small shadow-huge bg-green1-dark bottom-30 toggle-button" %>
      </div>
      <div class="one-half last-column">
        <%= link_to "구매하기", edit_order_path(@product), class: "button button-m button-full button-margins round-small shadow-huge bg-yellow1-light bottom-30" %>
      </div>
    <% else %>
      <div class="one-half">
        <a href="<%= new_user_session_path(notice: "로그인 후 이용해주세요") %>" class=" button button-m button-full button-margins round-small shadow-huge bg-green1-dark bottom-30 toggle-button">찜하기</a>
      </div>
      <div class="one-half last-column">
        <a href="<%= new_user_session_path(notice: "로그인 후 이용해주세요") %>" class=" button button-m button-full button-margins round-small shadow-huge bg-yellow1-light bottom-30">구매하기</a>
      </div>
    <% end %>
    <hr>
    <p>
      <%= simple_format(@product.short_desc) %>
    </p>
    <div class="divider"></div>
  </div>
  <a href="https://hirechance.org/product/esperanza-drip-bag-coffee-subscription/" target="_blank">
    <div data-height="70" class="caption caption-margins round-medium">
      <div class="caption-center left-20">
        <p class="bottom-0">
          <strong>아래 링크에서 더욱 자세한 정보를 확인하세요</strong>
        </p>
        <p class="bottom-0 font-10 under-heading"><%= @product.link %></p>
      </div>
      <div class="caption-center right-10">
        <i class="fa fa-chevron-right float-right opacity-15"></i>
      </div>
      <div class="caption-overlay bg-black opacity-10"></div>
    </div>
  </a>

  <div class="content">
    <div class="divider"></div>
    <h4>배송안내:</h4>
    <p class="color-highlight font-10 under-heading bottom-10">Delivery</p>
    <p>
      <%= simple_format(@product.delivery) %>
    </p>
    <div class="divider"></div>
  </div>

  <div class="content">
    <div class="divider"></div>
    <h4>교환/반품/환불:</h4>
    <p class="color-highlight font-10 under-heading bottom-10">Exchange / Return / Refund:</p>
    <p>
      <%= simple_format(@product.desc) %>
    </p>
    <div class="divider"></div>
  </div>

  <div class="divider divider-margins"></div>

  <a href="<%= products_path %>" class="button button-full button-m button-margins round-small shadow-huge bg-yellow1-light bottom-30">뒤로가기</a>
</div>

app/views/products/toggle.js.erb
<% if @toggle %>
  $(".toggle-button").removeClass("bg-green1-dark");
  $(".toggle-button").addClass("bg-red1-light");
  $(".toggle-button").html("찜취소");
<% else %>
  $(".toggle-button").removeClass("bg-red1-light");
  $(".toggle-button").addClass("bg-green1-dark");
  $(".toggle-button").html("찜하기");
<% end %>